# Generated by Django 5.0.6 on 2024-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='tags',
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='snippets', to='snipbox.tags'),
        ),
    ]
